[package]
name = "stretch"
version = "0.1.0"
authors = ["Emil Sjölander <emil@visly.app>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"
yoga = "0.3"

[[bench]]
name = "generated"
harness = false

[[bench]]
name = "comparative"
harness = false
